package com.cgihosting.entity;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import java.util.Date;

/**
 * Created by garnons on 02/12/2016.
 */

@Entity
@Table(name="appli_utilisateurs")
public class User {
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int a_uti_cle;

    @NotNull
    private String a_uti_prenom;

    @NotNull
    private String a_uti_nom;

    @NotNull
    private String a_uti_mail;

    @Null
    private String a_uti_telephone_fixe;

    @Null
    private String a_uti_telephone_mobi;

    @Null
    private Date a_uti_date_creation;

    @NotNull
    private int a_uti_type_utilisateur;

    @NotNull
    private String a_uti_code_cgi;

    @NotNull
    @Column(name="a_uti_identi_cgi")
    private String identi;

    @OneToMany
    private UserRole userRole;

    public User() {
    }

    public User(String a_uti_prenom, String a_uti_nom, String a_uti_mail, String a_uti_telephone_fixe, String a_uti_telephone_mobi, Date a_uti_date_creation, int a_uti_type_utilisateur, String identi, String a_uti_code_cgi) {
        this.a_uti_prenom = a_uti_prenom;
        this.a_uti_nom = a_uti_nom;
        this.a_uti_mail = a_uti_mail;
        this.a_uti_telephone_fixe = a_uti_telephone_fixe;
        this.a_uti_telephone_mobi = a_uti_telephone_mobi;
        this.a_uti_date_creation = a_uti_date_creation;
        this.a_uti_type_utilisateur = a_uti_type_utilisateur;
        this.identi = identi;
        this.a_uti_code_cgi = a_uti_code_cgi;
    }

    public int getA_uti_cle() {
        return a_uti_cle;
    }

    public void setA_uti_cle(int a_uti_cle) {
        this.a_uti_cle = a_uti_cle;
    }

    public String getA_uti_prenom() {
        return a_uti_prenom;
    }

    public void setA_uti_prenom(String a_uti_prenom) {
        this.a_uti_prenom = a_uti_prenom;
    }

    public String getA_uti_nom() {
        return a_uti_nom;
    }

    public void setA_uti_nom(String a_uti_nom) {
        this.a_uti_nom = a_uti_nom;
    }

    public String getA_uti_mail() {
        return a_uti_mail;
    }

    public void setA_uti_mail(String a_uti_mail) {
        this.a_uti_mail = a_uti_mail;
    }

    public String getA_uti_telephone_fixe() {
        return a_uti_telephone_fixe;
    }

    public void setA_uti_telephone_fixe(String a_uti_telephone_fixe) {
        this.a_uti_telephone_fixe = a_uti_telephone_fixe;
    }

    public String getA_uti_telephone_mobi() {
        return a_uti_telephone_mobi;
    }

    public void setA_uti_telephone_mobi(String a_uti_telephone_mobi) {
        this.a_uti_telephone_mobi = a_uti_telephone_mobi;
    }

    public Date getA_uti_date_creation() {
        return a_uti_date_creation;
    }

    public void setA_uti_date_creation(Date a_uti_date_creation) {
        this.a_uti_date_creation = a_uti_date_creation;
    }

    public int getA_uti_type_utilisateur() {
        return a_uti_type_utilisateur;
    }

    public void setA_uti_type_utilisateur(int a_uti_type_utilisateur) {
        this.a_uti_type_utilisateur = a_uti_type_utilisateur;
    }

    public String getIdenti() {
        return identi;
    }

    public void setIdenti(String identi) {
        this.identi = identi;
    }

    public String getA_uti_code_cgi() {
        return a_uti_code_cgi;
    }

    public void setA_uti_code_cgi(String a_uti_code_cgi) {
        this.a_uti_code_cgi = a_uti_code_cgi;
    }
}
