package com.cgihosting.entity;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by garnons on 05/12/2016.
 */
@Entity
@Table(name="appli_type_utilisateurs")
public class UserType {
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @NotNull
    @Column(name="a_typeutil_clef")
    private int cle;

    @NotNull
    @Column(name="a_typeutil_type")
    private String role;

    public int getCle() {
        return cle;
    }

    public void setCle(int cle) {
        this.cle = cle;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }
}
